analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4688745259772986
  brandStrength: 0.8960574
  lightness: 0.06769634084776044
  brandColors:
    - '#F9E5C2'
    - '#AC9E86'
    - '#000000'
    - '#6C6358'
    - '#2F2B23'
  rhythmicContrast: 0.7820571046322584
typography_spectrum: 0.06272402
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9964158
favicon: null
name: CharlotteSometimes
